### PR TITLE
feat:Updates danger workflow

### PR DESCRIPTION
**Pull request by hectorcustodiozup**
Signed-off-by: Hector Custódio <hector.custodio@zup.com.br>

### Description and Example
 - Added skip conditional fow workflows which are ran on external forked repositories.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.
- [x] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle-android/blob/main/doc/contributing/pull_requests.md

### CODE REVIEW

**Comment by uziassantosferreira** [comment]
@hectorcustodiozup I can open another PR fixing the  workflows and run the necessary things, do you mind if i do this?

**Comment by hectorcustodiozup** [comment]
> @hectorcustodiozup I can open another PR fixing the workflows and run the necessary things, do you mind if i do this?

Of course you can help. I am testing which workflows require mandatory secrets so I can keep them optional for external contributors and remove unnecessary keys from the files. Even if your PR passes I still have to keep it consistent for external cases like yours.

**Comment by uziassantosferreira** [comment]
@hectorcustodiozup yes I understand I will open another PR with these rules applied and some things related to workflow

**Comment by hectorcustodiozup** [comment]
> @hectorcustodiozup yes I understand I will open another PR with these rules applied and some things related to workflow

It seems that github actions do not offers a way to share secrets among forked repositories and for security reasons external tokens are ran on read-only mode access. I skipped the external owners and will test it as we can run these validations on our side.

Thanks again for the help!!!

**Pull request closed without merging**
