### PR TITLE
chore: adjust report to sonarqube

### PR DESCRIPTION
**Pull request by uziassantosferreira**
### Related Issues

Closes https://github.com/ZupIT/beagle/issues/1790

### Description and Example

coverage was not sending the correct report to Sonarqube with this code, everything has been fixed

Screen Shot 2021-12-04 at 16 51 14

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle-android/blob/main/doc/contributing/pull_requests.md

### CODE REVIEW

**Comment by uziassantosferreira** [comment]
i need help with this issue of the license in the header i put the correct date but it keeps failing, it would be interesting to put settings for intelij to create these files with the correct header that would help the developer.

**Comment by uziassantosferreira** [comment]
is there any reason for external contributions the jobs not run? these mistakes about secrets is on your side I can't do anything on my side

**Comment by hectorcustodiozup** [comment]
Hi @uziassantosferreira, thank you for you interest in contributing with Beagle.

I will take a look into it as soon as possible, the token secrets seemed to be ignored when repositories are forked, the license header is an internal tool of ours.

I am editing my message on the header license error:
The header should follow the pattern "Copyright startingYear, currenteYear..." in your case 2020, 2021 should fix the issue. But indeed the error alert could be improved and so I am opening a request of enhancement for the owners.

**Comment by uziassantosferreira** [comment]
@hectorcustodiozup but I change all files I created to 2021 and the error still happens x.x

**Comment by hectorcustodiozup** [comment]
> @hectorcustodiozup but I change all files I created to 2021 and the error still happens x.x

Yes, but the copyrights requests initial and final years, so, as I left in my comment for your case the correct copyright is Copyright 2020, 2021 ...

**Comment by uziassantosferreira** [comment]
@hectorcustodiozup thanks I fixed

**Comment by uziassantosferreira** [comment]
@hectorcustodiozup can you see this PR <3

**Comment by hectorcustodiozup** [comment]
Hi @uziassantosferreira, 

We are currently working on some other demands but we are aware of your pull request and will soon be tested and reviewed.

Thanks

**Review by hectorcustodiozup — APPROVED** [review]

**Pull request merged**
